### ISSUE TITLE
定義されていない パス（customers_path） が使われている

### ISSUE THREAD

**Issue by aomrikti** [hybitz/hyacc#37]
下記の2ファイルで　`<%= link_to '取引先管理へ', customers_path %>`  のコードがあるが、`customers_path` は定義されていない。他ファイルでは `mm_customers_path` が使われている。
- app/views/mm/rents/check_customer_exists.html.erb
- app/views/simple_slips/sub_accounts_required.html.erb

**Comment by ichylinux** [comment]
@aomrikti 

本件の対応をお願いします。

**Comment by aomrikti** [comment]
修正結果
【「売掛金」画面】
- app/views/simple_slips/sub_accounts_required.html.erb
![スクリーンショット 2024-12-09 170352](https://github.com/user-attachments/assets/a642e96d-79ab-4c2c-b840-cb674c413a03)
- 「取引先管理へ」をクリック後に遷移できることを確認
![スクリーンショット 2024-12-09 170800](https://github.com/user-attachments/assets/9bfb3148-ecfc-48e4-8500-c9df6c785b37)

【「地代家賃」画面】

- app/views/simple_slips/sub_accounts_required.html.erb
![スクリーンショット 2024-12-09 170617](https://github.com/user-attachments/assets/3db922e0-8a80-4ade-8f71-8c309211de6e)
- 「取引先管理へ」をクリック後に遷移できることを確認
![スクリーンショット 2024-12-09 170741](https://github.com/user-attachments/assets/02d259ae-dbfd-468f-9741-818b286422db)

**Comment by ichylinux** [comment]
@aomrikti 

ご対応ありがとうございます。

修正前の状態で、テストケースを用意して問題を再現し、修正したら問題が解消した、というテストファーストなアプローチを（すでに後付けですが）とれるでしょうか？

**Comment by aomrikti** [comment]
@ichylinux
下記のとおりテストケースを作成しました。
レビューをお願いします。

>テストファーストなアプローチを（すでに後付けですが）とれるでしょうか？

承知しました。今後は修正前にテストケースを用意するアプローチで取り組みます。

===
【テストケース】
- user_stories/01期/2013-06.起業.feature
```
  シナリオ: 資本金の登録
    会社の設立に必要な資金を登録する。

    * 金融機関を登録
    * 口座を登録
    * よく使う科目にショートカットキーを設定
    * ショートカットキーからアクセスした科目の補助科目が必須の場合でまだ補助科目が存在しない場合は補助科目の管理画面へ誘導　# 追加
    * サブメニューからアクセスした科目の補助科目が必須でまだ補助科目が存在しない場合は補助科目の管理画面へ誘導　# 追加
...
```
- user_stories/step_definitions/simple_slips.rb
```
もし /^ショートカットキーからアクセスした科目の補助科目が必須の場合でまだ補助科目が存在しない場合は補助科目の管理画面へ誘導$/ do
  click_on '3.売掛金'
  assert_text '受注先が登録されていません。'
  assert has_link?("取引先管理へ", href: /#{mm_customers_path}*/)
end

もし /^サブメニューからアクセスした科目の補助科目が必須でまだ補助科目が存在しない場合は補助科目の管理画面へ誘導$/ do
  click_on 'マスタメンテ'
  within ".subMenu" do
    click_on '地代家賃'
  end
  assert_text '地代家賃の設定には取引先の登録が必要です。'
  assert has_link?("取引先管理へ", href: mm_customers_path)
end
```
【結果】
```
$ bundle exec rake dad:test user_stories  DRIVER=selenium
...
40 scenarios (40 passed)
68 steps (68 passed)
16m47.422s
```

**Comment by ichylinux** [comment]
@aomrikti 

ご対応ありがとうございます。

#36 のように、ロジック修正前の状態にして、テストケースがエラーになるというエビデンスも取得いただけますか？

**Comment by ichylinux** [comment]
別口でのテストケースを追加しました。

```ruby
  def test_一覧_取引先マスタが未登録
    Customer.delete_all

    get :index
    assert_response :success
    assert_template 'check_customer_exists'
  end
```

対応前の状態に戻した場合

```
$ rails test test/controllers/mm/rents_controller_test.rb
Run options: --seed 61587

# Running:
.

Finished in 2.569037s, 3.1140 runs/s, 5.8388 assertions/s.

  1) Error:
Mm::RentsControllerTest#test_一覧_取引先マスタが未登録:
RuntimeError: Neutered Exception ActionView::Template::Error: undefined local variable or method `customers_path' for #<#<Class:0x0000000005b11340>:0x0000000005e46768>
Did you mean?  mm_users_path
    app/views/mm/rents/check_customer_exists.html.erb:3:in `_app_views_mm_rents_check_customer_exists_html_erb__1576941562785467388_29000'
    app/controllers/mm/rents_controller.rb:72:in `check_customer_exists'
    test/controllers/mm/rents_controller_test.rb:18:in `test_一覧_取引先マスタが未登録'

8 runs, 15 assertions, 0 failures, 1 errors, 0 skips
```

対応後

```
$ rails test test/controllers/mm/rents_controller_test.rb
Run options: --seed 19944

# Running:

Finished in 2.654638s, 3.0136 runs/s, 6.4039 assertions/s.

8 runs, 17 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by aomrikti** [comment]
@ichylinux 

ご指摘ありがとうございます。
対応前の状態に戻して実行した結果が、下記となります。
今後は、対応前の `テストケースがエラーになるというエビデンス` を記録してから作業を進めるように注意します。

#### 対応前の状態に戻した場合（ファイルごとに戻して都度実行）
- app/views/simple_slips/sub_accounts_required.html.erb
```
$ bundle exec rake dad:test user_stories

    * ショートカットキーからアクセスした科目の補助科目が必須の場合でまだ補助科目が存在しない場合は補助科目の管理画面へ誘導 # user_stories/step_definitions/simple_slips.rb:1
      Expected false to be truthy. (Minitest::Assertion)
      ./user_stories/step_definitions/simple_slips.rb:4:in `/^ショートカットキーからアクセスした科目の補助科目が必須の場合でまだ補助科目が存在しない場合は補助科目の管理画面へ誘導$/'
      user_stories/01期/2013-06.起業.feature:32:in `ショートカットキーからアクセスした科目の補助科目が必須の場合でまだ補助科目が存在しない場合は補助科目の管理画面へ誘導'
    * サブメニューからアクセスした科目の補助科目が必須でまだ補助科目が存在しない場合は補助科目の管理画面へ誘導       # user_stories/step_definitions/simple_slips.rb:7
    * 資本金の仕訳を登録                                                  # user_stories/step_definitions/simple_slips.rb:16
2024-12-11 10:44 Rack app ("GET /simple/1551" - (127.0.0.1)): #<ActionView::Template::Error: undefined local variable or method `customers_path' for #<#<Class:0x00007f0eb46323f0>:0x00007f0eb46305a0>
Did you mean?  mm_users_path>
      undefined local variable or method `customers_path' for #<#<Class:0x00007f0eb46323f0>:0x00007f0eb46305a0>
      Did you mean?  mm_users_path (ActionView::Template::Error)
      ./app/views/simple_slips/sub_accounts_required.html.erb:15:in `_app_views_simple_slips_sub_accounts_required_html_erb___371778931844825095_73020'
      ./app/controllers/simple_slips_controller.rb:243:in `check_sub_accounts'

Failing Scenarios:
cucumber user_stories/01期/2013-06.起業.feature:26 # シナリオ: 資本金の登録

2 scenarios (1 failed, 1 passed)
9 steps (1 failed, 2 skipped, 6 passed)
0m53.320s
rake aborted!
```

- app/views/simple_slips/sub_accounts_required.html.erb
```
$ bundle exec rake dad:test user_stories
...
* サブメニューからアクセスした科目の補助科目が必須でまだ補助科目が存在しない場合は補助科目の管理画面へ誘導       # user_stories/step_definitions/simple_slips.rb:7
      Expected false to be truthy. (Minitest::Assertion)
      ./user_stories/step_definitions/simple_slips.rb:13:in `/^サブメニューからアクセスした科目の補助科目が必須でまだ補助科目が存在しない場合は補助科目の管理画面へ誘導$/'
      user_stories/01期/2013-06.起業.feature:33:in `サブメニューからアクセスした科目の補助科目が必須でまだ補助科目が存在しない場合は補助科目の管理画面へ誘導'
    * 資本金の仕訳を登録                                                  # user_stories/step_definitions/simple_slips.rb:16
2024-12-11 10:47 Rack app ("GET /mm/rents" - (127.0.0.1)): #<ActionView::Template::Error: undefined local variable or method `customers_path' for #<#<Class:0x00007eff9001cc28>:0x00007eff9001af40>
Did you mean?  mm_users_path>
      undefined local variable or method `customers_path' for #<#<Class:0x00007eff9001cc28>:0x00007eff9001af40>
      Did you mean?  mm_users_path (ActionView::Template::Error)
      ./app/views/mm/rents/check_customer_exists.html.erb:3:in `_app_views_mm_rents_check_customer_exists_html_erb__913558774583751117_73300'
      ./app/controllers/mm/rents_controller.rb:72:in `check_customer_exists'

Failing Scenarios:
cucumber user_stories/01期/2013-06.起業.feature:26 # シナリオ: 資本金の登録

2 scenarios (1 failed, 1 passed)
9 steps (1 failed, 1 skipped, 7 passed)
0m52.941s
rake aborted!
```

#### 対応後
```
$ bundle exec rake dad:test user_stories
...
40 scenarios (40 passed)
68 steps (68 passed)
16m32.447s
```

**Comment by aomrikti** [comment]
>別口でのテストケースを追加しました。

作成ありがとうございます。
エラーの解消がより的確に理解でき、より適切であると感じます。
わざわざuser_storiesに加える必要はなかったと気づかされました。

今後は過不足がなく、的確にテストケースを書くことを心掛けて取り組みます。

**Comment by ichylinux** [comment]
@aomrikti 

エビデンス取得ありがとうございます。

今回、単体テスト（コントローラテスト）を１つこちらで追加しました。
修正箇所がもう１つありましたね、そちらについてもテストケースの追加をお願いします。

**Comment by aomrikti** [comment]
@ichylinux 

ご指摘ありがとうございます。
単体テストのテストケースを下記の通り追加いたしました。

- test/controllers/simple_slips_controller/check_sub_accounts_test.rb(新規作成)
```rb
require 'test_helper'

class SimpleSlipsController::CheckSubAccountsTest < ActionController::TestCase

  def setup
    sign_in user
  end

  def test_一覧_取引先マスタが未登録
    Customer.delete_all
    get :index, params: {account_code: ACCOUNT_CODE_RECEIVABLE}
    assert_template "sub_accounts_required"
  end

end
```
- 対応前の状態に戻した場合
```
$ rails test test/controllers/simple_slips_controller/check_sub_accounts_test.rb
Run options: --seed 24801

# Running:

E

Finished in 2.032367s, 0.4920 runs/s, 0.0000 assertions/s.

  1) Error:
SimpleSlipsController::CheckSubAccountsTest#test_一覧_取引先マスタが未登録:
RuntimeError: Neutered Exception ActionView::Template::Error: undefined local variable or method `customers_path' for #<#<Class:0x000055fe3a473478>:0x000055fe3b367a10>
Did you mean?  mm_users_path
    app/views/simple_slips/sub_accounts_required.html.erb:15:in `_app_views_simple_slips_sub_accounts_required_html_erb___3911054218154838827_29020'
    app/controllers/simple_slips_controller.rb:243:in `check_sub_accounts'
    test/controllers/simple_slips_controller/check_sub_accounts_test.rb:10:in `test_一覧_取引先マスタが未登録'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```
- 対応後
```
$ rails test test/controllers/simple_slips_controller/check_sub_accounts_test.rb
Run options: --seed 34668

# Running:
.

Finished in 4.244998s, 0.2356 runs/s, 0.2356 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by ichylinux** [comment]
@aomrikti 

ご対応ありがとうございます。

さて、以前のコメントで、

```
わざわざuser_storiesに加える必要はなかった
```

とコメントいただいています。
この「わざわざ」が端的に **テストピラミッド** について有意な経験を物語っていると思います。
可能な限り時間のかかるE2Eテストではなく、軽快な単体テストで細かなテストをしたいものです。

Cucumberのフィーチャテストである user_stories については、元の状態に戻していただたいたほうが良いと思います。
テストピラミッドの概念について確認いただき、ある種のロールプレイとして元の状態に戻すという立場の根拠とともに、ご対応お願いします。

**Comment by aomrikti** [comment]
@ichylinux 

本Issueのテスト対象はそれぞれrentsコントローラーのcheck_customer_existsメソッド、simple_slipsコントローラーのcheck_sub_accountsメソッドであり、別のシステムを必要としない単一のプロセスで実行できるため、単体テストでのテストが適しています。テストピラミッドの概念より記述コスト・実行コストが高いE2Eテストは可能な限り少なく、費用対効果が大きい単体テストが最も多いというバランスが望ましく、本IssueをE2Eテストの対象とする事は概念に反していると考えます。結果として、E2Eテストに追加したテストケースは削除しました。

**Comment by ichylinux** [comment]
@aomrikti 

ご対応ありがとうございます。
的確な分析に思います。

これにて本対応はすべてと完了と思います。
クローズします。
