### ISSUE TITLE
定義されていない パス が使われている

### ISSUE THREAD

**Issue by aomrikti** [hybitz/hyacc#40]
定義されていないパスが使われている箇所を調査し、修正する

**Comment by aomrikti** [comment]
再現テストケース（app/views/simple_slips/sub_accounts_required.html.erb）
```rb
  def test_一覧_金融口座マスタが未登録
    BankAccount.delete_all
    get :index, params: {account_code: ACCOUNT_CODE_ORDINARY_DIPOSIT}
    assert_template "sub_accounts_required"
  end

  def test_一覧_地代家賃マスタが未登録
    Rent.delete_all
    get :index, params: {account_code: ACCOUNT_CODE_RENT}
    assert_template "sub_accounts_required"
  end
```
```
$ rails test test/controllers/simple_slips_controller/check_sub_accounts_test.rb
Run options: --seed 30464

# Running:

.EE

Finished in 5.114112s, 0.5866 runs/s, 0.1955 assertions/s.

  1) Error:
SimpleSlipsController::CheckSubAccountsTest#test_一覧_金融口座マスタが未登録:
RuntimeError: Neutered Exception ActionView::Template::Error: undefined local variable or method `bank_accounts_path' for #<#<Class:0x000055a0487d0580>:0x000055a04c272558>
Did you mean?  sub_accounts_path
               mm_bank_accounts_path
    app/views/simple_slips/sub_accounts_required.html.erb:9:in `_app_views_simple_slips_sub_accounts_required_html_erb__241782308844258505_29000'
    app/controllers/simple_slips_controller.rb:243:in `check_sub_accounts'
    test/controllers/simple_slips_controller/check_sub_accounts_test.rb:17:in `test_一覧_金融口座マスタが未登録'

  2) Error:
SimpleSlipsController::CheckSubAccountsTest#test_一覧_地代家賃マスタが未登録:
RuntimeError: Neutered Exception ActionView::Template::Error: undefined local variable or method `rents_path' for #<#<Class:0x000055a0487d0580>:0x000055a046cbbfb0>
Did you mean?  debts_path
               root_path
    app/views/simple_slips/sub_accounts_required.html.erb:27:in `_app_views_simple_slips_sub_accounts_required_html_erb__241782308844258505_29000'
    app/controllers/simple_slips_controller.rb:243:in `check_sub_accounts'
    test/controllers/simple_slips_controller/check_sub_accounts_test.rb:23:in `test_一覧_地代家賃マスタが未登録'
```

**Comment by aomrikti** [comment]
再現テストケース（app/views/bs/investments/not_related.html.erb）
```rb
  def test_not_related
    JournalDetail.first.update(account_id: Account.find_by(code: ACCOUNT_CODE_TRADING_SECURITIES).id)
    get :not_related
    assert_response :success
  end
```
```
$ rails test test/controllers/bs/investments_controller_test.rb
Run options: --seed 58645

# Running:

.E.

Finished in 5.918724s, 0.8448 runs/s, 1.1827 assertions/s.

  1) Error:
Bs::InvestmentsControllerTest#test_not_related:
RuntimeError: Neutered Exception ActionView::Template::Error: undefined method `relate_investments_path' for #<#<Class:0x00005562c9d5d0a0>:0x00005562cce9def8>
Did you mean?  relate_bs_investments_path
    app/views/bs/investments/not_related.html.erb:22:in `block in _app_views_bs_investments_not_related_html_erb__1756316483232785311_29760'
    app/views/bs/investments/not_related.html.erb:14:in `each'
    app/views/bs/investments/not_related.html.erb:14:in `_app_views_bs_investments_not_related_html_erb__1756316483232785311_29760'
    test/controllers/bs/investments_controller_test.rb:39:in `test_not_related'
```
※上記のエラー修正後、テストを再実行
```
$ rails test test/controllers/bs/investments_controller_test.rb
Run options: --seed 15343

# Running:
..

Finished in 5.880052s, 0.8503 runs/s, 1.1905 assertions/s.

  1) Error:
Bs::InvestmentsControllerTest#test_not_related:
RuntimeError: Neutered Exception ActionView::Template::Error: undefined local variable or method `investments_path' for #<#<Class:0x0000557a6afd8a88>:0x0000557a6d49f268>
Did you mean?  bs_investment_path
               bs_investments_path
    app/views/bs/investments/not_related.html.erb:27:in `_app_views_bs_investments_not_related_html_erb___3961972137795721073_29680'
    test/controllers/bs/investments_controller_test.rb:39:in `test_not_related'
```

**Comment by aomrikti** [comment]
@ichylinux 
本件対応しました。
レビューをお願いします。
```
$ rails test test/controllers/simple_slips_controller/check_sub_accounts_test.rb
Run options: --seed 63107

# Running:
...

Finished in 4.624474s, 0.6487 runs/s, 0.6487 assertions/s.

3 runs, 3 assertions, 0 failures, 0 errors, 0 skips
```
```
$ rails test test/controllers/bs/investments_controller_test.rb
Run options: --seed 22740

# Running:
..

Finished in 5.707819s, 0.8760 runs/s, 1.4016 assertions/s.

5 runs, 8 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by ichylinux** [comment]
@aomrikti 

ご対応ありがとうございます。
気になる点はありませんでした。

本件クローズします。
