### ISSUE TITLE
従業員の詳細画面で退職金の積立が何年何月から開始になるのかわかる表示をする

### ISSUE THREAD

**Issue by ichylinux** [hybitz/hyacc#44]
#43 の後続タスク

**Comment by aomrikti** [comment]
テストケース
- features/09.マスタメンテ/02.従業員.feature
```
  シナリオ: 詳細ダイアログで退職金積立開始時期を表示する
    前提 経理次郎がログインしている
    前提 退職金積立開始時期が入社から3年目に登録されている
    * マスタメンテから従業員のメニューを選択する
    * 従業員の詳細ダイアログに以下のように表示される
     | 従業員 | 入社日 | 退職金積立開始時期 |
     | 本店 一郎 | 2009-01-01 | 2011年1月 |
     | 経理 次郎 | 2009-01-01 | 2011年1月 |
```
```
$ bundle exec rake dad:test features/09.マスタメンテ/02.従 業員.feature

(省略)

  シナリオ: 詳細ダイアログで退職金積立開始時期を表示する  # features/09.マスタメンテ/02.従業員.feature:9
    前提経理次郎がログインしている             # features/step_definitions/common.rb:1
    前提退職金積立開始時期が入社から3年目に登録されている # features/step_definitions/employees.rb:1
    * マスタメンテから従業員のメニューを選択する     # features/step_definitions/employees.rb:5
      <img class="screenshot" src="images/3.png" alt="http://127.0.0.1:39789/mm/employees" />
    * 従業員の詳細ダイアログに以下のように表示される   # features/step_definitions/employees.rb:31
      Expected false to be truthy. (Minitest::Assertion)
      ./features/step_definitions/employees.rb:58:in `block (3 levels) in <main>'
      ./features/step_definitions/employees.rb:57:in `block (2 levels) in <main>'
      ./features/step_definitions/employees.rb:33:in `each'
      ./features/step_definitions/employees.rb:33:in `/^従業員の詳細ダイアログに以下のように表示される$/'
      features/09.マスタメンテ/02.従業員.feature:13:in `従業員の詳細ダイアログに以下のように表示される'
      <img class="screenshot" src="images/4.png" alt="http://127.0.0.1:39789/mm/employees" />

Failing Scenarios:
cucumber features/09.マスタメンテ/02.従業員.feature:9 # シナリオ: 詳細ダイアログで退職金積立開始時期を表示する

2 scenarios (1 failed, 1 passed)
6 steps (1 failed, 5 passed)
0m36.005s

Randomized with seed 39196
rake aborted!
```

**Comment by aomrikti** [comment]
@ichylinux 
修正しました。テスト結果とエビデンスは下記のとおりです。
レビューをお願いいたします。
- テスト結果
```
$ bundle exec rake dad:test features/09.マスタメンテ/02.従 業員.feature

（省略）

2 scenarios (2 passed)
6 steps (6 passed)
0m27.446s
```
- 表示箇所は従業員の詳細画面の右（_evaluation.html.erbの最後に追加）

![image.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/3570127/0a100d0e-4bc5-3adb-8a71-702f51308439.png)

**Comment by aomrikti** [comment]
【追加の修正】
#43 範囲のマスタメンテ/会社の退職金積立開始時期行の値を削除しても「入社年目から」の表示が残るバグがありましたので、修正しました。https://github.com/hybitz/hyacc/commit/ce015f24ee5ddc051655072b630a31e92d005530
- 修正前
![スクリーンショット 2025-01-29 140734.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/3570127/93fe1283-b39c-4e9c-3330-25dad99d45a6.png)
- 修正後
![スクリーンショット 2025-01-29 140753.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/3570127/8a992a39-e83f-e7ba-0b0d-2b32c2b91463.png)

**Comment by ichylinux** [comment]
@aomrikti 

ご対応ありがとうございます。

ここまでの傾向を見ると、テストケースとしてフィーチャテストを作成する傾向が強いように思います。
テストピラミッド的には E2E テストは時間がかかりますし、実際に実装をしている時に繰り返しテストケースを実行する時の待ち時間もそれなりにあったのではないでしょうか？

今回の対応の場合、ヘルパーメソッドの単体テストがしっかりできていれば、画面に表示されているかどうかは一度確認すれば、その後にそうそう表示されなくなっているというデグレの心配はないのではないでしょうか？

ひとまずヘルパーメソッドの単体テストを用意してみてください。

**Comment by aomrikti** [comment]
@ichylinux 
ご指摘ありがとうございます。
単体テストでも書けますね。。フィーチャテストに「わざわざ」書くべきではありませんでした。

早速単体テストを追加しました。結果は下記のとおり確認しました。
```
$ rails test test/helpers/mm/employees_helper_test.rb

Finished in 1.278044s, 1.5649 runs/s, 7.0420 assertions/s.

2 runs, 9 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by ichylinux** [comment]
@aomrikti 

テストケース単体を rails test test/helpers/... と個別に指定して実行したら、フィーチャテストよりテスト実行時間が短いと思いますがどうでしたか？

あと、Employee は belongs_to :company と定義されているので、 `Company.find(employee.company_id)` とまっさらな会社オブジェクトを取得せずに、関連モデルとして会社オブジェクトを使用するようにリファクタリングをお願いします。

会社オブジェクトが何度も必要になった時に、関連オブジェクトであればキャッシュが効いていて効率がよいです。

**Comment by aomrikti** [comment]
@ichylinux 
テスト実行時間は単体テストが1秒強で、フィーチャテストは30秒前後ですので圧倒的に時間の短縮になることを理解しました。
今後はフィーチャテストは単体テストで書けないもののみと認識を徹底します。

`Company.find(employee.company_id)` を `employee.company` にリファクタリングしました。今後も留意いたします。
フィーチャテストの削除・リファクタリング後のテスト結果も確認しました。
```
$ rails test test/helpers/mm/employees_helper_test.rb

Finished in 1.235421s, 1.6189 runs/s, 7.2850 assertions/s.

2 runs, 9 assertions, 0 failures, 0 errors, 0 skips
```
```
$ bundle exec rake dad:test features/09.マスタメンテ/02.従 業員.feature

1 scenario (1 passed)
2 steps (2 passed)
0m30.873s
```

**Comment by ichylinux** [comment]
@aomrikti 

かなり時間差がありますね。

ちなみに松田の10年くらい前に購入したデスクトップマシンでの実行結果です。

```
$ rails test test/helpers/mm/employees_helper_test.rb
Running via Spring preloader in process 12551
Run options: --seed 6998

# Running:

..

Finished in 0.497195s, 4.0226 runs/s, 18.1016 assertions/s.

2 runs, 9 assertions, 0 failures, 0 errors, 0 skips
```

```
$ bundle exec rake dad:test features/09.マスタメンテ/02.従業員.feature

2 scenarios (2 passed)
6 steps (6 passed)
0m7.659s
```

当時では最新レベルのスペックでしたが、今でもまだまだ現役のパフォーマンスのようです。

**Comment by ichylinux** [comment]
@aomrikti 

さて、テストケースについてですが、入社月がどれもこれも1月のものばかりのように見えます。
2月とか10月とか別の入社月の社員であっても入社後2年を経過してから、というのがわかるようなテストケースにバリエーションを調整していただけますか？

**Comment by aomrikti** [comment]
@ichylinux 
>2月とか10月とか別の入社月の社員であっても入社後2年を経過してから、というのがわかるようなテストケースにバリエーションを調整していただけますか？

対応したものをコミットしました。
結果は下記のとおりです。
```
$ rails test test/helpers/mm/employees_helper_test.rb
Running via Spring preloader in process 4738
Run options: --seed 193

# Running:

..

Finished in 1.742330s, 1.1479 runs/s, 3.4437 assertions/s.

2 runs, 6 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by ichylinux** [comment]
@aomrikti 

あれ、月が変わることがテストケースでわかるようになりまsちあが、今度は、いつ入社しても 2022 年というロジックになっているかもしれない疑惑が出てきましたね。

**Comment by aomrikti** [comment]
@ichylinux 
下記のとおり、入社年・月、retirement_savings_safterにバリエーションがあるよう変更しました。
レビューをお願いいたします。
```rb
  def test_get_start_ym_of_retirement_savings
    company = Company.first
    company.update!(retirement_savings_after: 1)
    employees = Employee.where(company_id: company.id)
    employees[0].update!(employment_date: '20200101')
    employees[1].update!(employment_date: '20210201')
    employees[2].update!(employment_date: '20220701')
    assert_equal ['2020年1月', '2021年2月', '2022年7月'], [get_start_ym_of_retirement_savings(employees[0]), get_start_ym_of_retirement_savings(employees[1]), get_start_ym_of_retirement_savings(employees[2])]

    company.update!(retirement_savings_after: 2)
    employees = Employee.where(company_id: company.id)
    assert_equal ['2021年1月', '2022年2月', '2023年7月'],  [get_start_ym_of_retirement_savings(employees[0]), get_start_ym_of_retirement_savings(employees[1]), get_start_ym_of_retirement_savings(employees[2])]
    
    company.update!(retirement_savings_after: 3)
    employees = Employee.where(company_id: company.id)
    assert_equal ['2022年1月', '2023年2月', '2024年7月'],  [get_start_ym_of_retirement_savings(employees[0]), get_start_ym_of_retirement_savings(employees[1]), get_start_ym_of_retirement_savings(employees[2])]
  end
```
```
$ rails test test/helpers/mm/employees_helper_test.rb
Running via Spring preloader in process 6861
Run options: --seed 42393

# Running:

..

Finished in 2.028843s, 0.9858 runs/s, 2.9574 assertions/s.

2 runs, 6 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by ichylinux** [comment]
@aomrikti 

ご対応ありがとうございます。
テストケースの改善によって、実際のロジックがテストケースをパスさせるためだけのハリボテではないことがよく分かりましたw

本件終了いたします。
