### ISSUE TITLE
本締めとなっている年度の所得税控除の編集・削除ボタンを非表示に

### ISSUE THREAD

**Issue by ichylinux** [hybitz/hyacc#49]
今は、過去の暦年の所得税控除に対して編集と削除のボタン（リンク）が表示されている。

**Comment by aomrikti** [comment]
再現テストケース（所得税控除情報を未登録でも追加画面が表示されること）
```
# test/controllers/mm/excemptions_controller_test.rb
 def test_追加_所得税控除情報を未登録でも追加画面が表示されること
    Exemption.where(employee_id: @employee_id).delete_all
    sign_in admin
    get :new, params: {exemption: {employee_id: @employee_id}}, xhr: true
    assert_response :success
    assert_template :new
  end
```
```
$ rails test test/controllers/mm/exemptions_controller_test.rb:24

  1) Error:
Mm::ExemptionsControllerTest#test_追加_所得税控除情報を未登録でも追加画面が表示されること:
NoMethodError: undefined method `yyyy=' for nil:NilClass
    app/controllers/mm/exemptions_controller.rb:17:in `new'
    test/controllers/mm/exemptions_controller_test.rb:27:in `test_追加_所得税控除情報を未登録でも追加画面が表示されること'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by aomrikti** [comment]
再現テストケース（本締の年度は編集・削除ボタンは非表示）
```
# features/09.マスタメンテ/14.所得税控除.feature
# language: ja

機能: 所得税控除
  シナリオ: 本締となった会計年度の所得税控除の編集と削除ボタンは表示されない
    前提 本店 一郎の会社の会計年度の締め状態は下記の通り設定されている
     | 会計年度 | 締め状態 |
     | 2010 | 本締 |
     | 2011 | 仮締 |
     | 2012 | 通常 |
    前提 マスタメンテから所得税控除のメニューを選択する

    もし 暦年が2010年、従業員が本店 一郎の所得税控除の情報を取得する
    ならば 編集と削除ボタンは表示されない

    もし 暦年が2011年、従業員が本店 一郎の所得税控除の情報を取得する
    ならば 編集と削除ボタンは表示される

    もし 暦年が2012年、従業員が本店 一郎の所得税控除の情報を取得する
    ならば 編集と削除ボタンは表示される
```
```
$  bundle exec rake dad:test features/09.マスタメンテ/14.所得税控除.feature

（省略）

    ならば編集と削除ボタンは表示されない                   # features/step_definitions/exemption.rb:30
      Expected true to be nil or false (Minitest::Assertion)
      ./features/step_definitions/exemption.rb:37:in `/^編集と削除ボタンは(表示される|表示されない)$/'
      features/09.マスタメンテ/14.所得税控除.feature:13:in `編集と削除ボタンは表示されない'
    もし暦年が2011年、従業員が本店 一郎の所得税控除の情報を取得する   # features/step_definitions/exemption.rb:24
    ならば編集と削除ボタンは表示される                    # features/step_definitions/exemption.rb:30
    もし暦年が2012年、従業員が本店 一郎の所得税控除の情報を取得する   # features/step_definitions/exemption.rb:24
    ならば編集と削除ボタンは表示される                    # features/step_definitions/exemption.rb:30
      <img class="screenshot" src="images/1.png" alt="http://127.0.0.1:40728/mm/exemptions?finder[calendar_year]=2010&finder[employee_id]=1&commit=表示" />

Failing Scenarios:
cucumber features/09.マスタメンテ/14.所得税控除.feature:4 # シナリオ: 本締となった会計年度の所得税控除の編集と削除ボタンは表示されない

1 scenario (1 failed)
8 steps (1 failed, 4 skipped, 3 passed)
0m19.214s
```

**Comment by aomrikti** [comment]
@ichylinux 
本件対応しました。
レビューをお願いします。
- テスト結果
```
$ rails test test/controllers/mm/exemptions_controller_test.rb:24
Running via Spring preloader in process 29397
Run options: --seed 36990

# Running:

.

Finished in 2.165577s, 0.4618 runs/s, 0.9235 assertions/s.

1 runs, 2 assertions, 0 failures, 0 errors, 0 skips
```
```
$  bundle exec rake dad:test features/09.マスタメンテ/14.所得税控除.feature

（省略）

1 scenario (1 passed)
8 steps (8 passed)
0m26.292s
```
- 所得税控除の一覧画面（一番下の行の2022年を「本締」に設定した場合）
![スクリーンショット 2025-01-10 183726](https://github.com/user-attachments/assets/2156a8b0-6b73-48e7-882b-3c14fd936572)

**Comment by ichylinux** [comment]
@aomrikti 

ご対応ありがとうございます。

```
unless FiscalYear.find_by(company_id: e.company_id, fiscal_year: e.yyyy)&.closed?
```

ですが、 `&.closed?` と & を使っていることから、登録されている所得税控除が会社の経営が始まって以降のどの会計年度にも含まれない暦年に関する場合の時があるということだと思います。

会計年度の１年間が4月から始まって3月で終わるという会社が、例えば 2023年6月に起業されたとします。

この時、 & が考慮しているのは、登録されている所得税控除の暦年が、2022年、2023年、2024年、2025年のどの年の場合を危惧しているのか確認させてください。

この所得税控除のデータは年末調整で使用されるものですね。現在の日付が2024年4月以降の2024年のどこか（例えば2024年11月10日など）であった場合、

* 暦年が2022年分・・・2022年12月の年末調整のためのものだけれど、その時はまだ会社は存在しない
* 暦年が2023年分・・・2023年12月の年末調整のためのもので、この年末を含む2023年4月から2024年3月の期間の会計年度2023年度は決算が終わって本締めであると思われるため、編集・削除の対象外
* 暦年が2024年分・・・2024年12月の年末調整のためのもので、今年度であることから経理事務が行われていて本締めにはなっていないはずで、編集・削除が可能
* 暦年が2025年分・・・2025年12月の年末調整のためのものだけれど、まだ今は2024年なので、未来の話になるので本締め状態は考えにくい

このような状態に思います。

この2025年分の所得税控除が登録されているけど、まだ経理事務は発生しない未来だから会計年度マスタが存在しない、というケースを危惧されていますか？

**Comment by aomrikti** [comment]
@ichylinux 

>この2025年分の所得税控除が登録されているけど、まだ経理事務は発生しない未来だから会計年度マスタが存在しない、というケースを危惧されていますか？

はい、ご推測の通りに考えていたため、`&.closed?` としてしまいました。
`この所得税控除のデータは年末調整で使用されるものですね。` というご指摘で上記のケースが発生しないということをあらためて理解いたしました。

**Comment by aomrikti** [comment]
`&.closed?` と　`.closed?`　に訂正しました。
会計年度マスタが存在しない所得税控除マスタのデータがあるため、コントローラテストとフィーチャテスト（リファクタリングあり）に下記を追加し、会計年度マスタが存在する暦年のデータに絞っています。
```rb
years = Exemption.where(company_id: 1).pluck(:yyyy)
years.map{|y| FiscalYear.find_by(company_id: 1, fiscal_year: y).blank? ? Exemption.where(yyyy: y).delete_all : next }`
```
```
$ rails test test/controllers/mm/exemptions_controller_test.rb
Running via Spring preloader in process 47559
Run options: --seed 10628

# Running:

Finished in 11.477202s, 0.6970 runs/s, 2.7010 assertions/s.

8 runs, 31 assertions, 0 failures, 0 errors, 0 skips
```

```
$ bundle exec rake dad:test features/09.マスタメンテ/14.所 得税控除.feature


1 scenario (1 passed)
5 steps (5 passed)
0m26.124s
```

**Comment by ichylinux** [comment]
@aomrikti 

ご確認ありがとうございます。

てっきり、 & がないとエラーになったので & を入れたのかなと思ったのですが、エラーになったから入れたわけではなく、あらかじめ考慮した、ということでしたか？

というのも、もしエラーになったなら & での対策ではなく、所得税控除の登録時に当該暦年を含む会計年度が存在しないというのがおかしな状況なのかなと思いました。

> 会計年度マスタが存在しない所得税控除マスタのデータがあるため、コントローラテストとフィーチャテスト（リファクタリングあり）に下記を追加し、会計年度マスタが存在する暦年のデータに絞っています。

とコメントいただいているように、 `会計年度マスタが存在しない所得税控除マスタのデータがある` という状況を入力チェックとして防ぐと良いのではないかと思いましたが、いかがでしょうか？

**Comment by aomrikti** [comment]
>エラーになったから入れたわけではなく、あらかじめ考慮した、ということでしたか？

あらかじめの考慮ではなく、エラーが出たから対応したという方が正しいと思います。
そもそも所得税控除の処理を年末に行うという考慮をしていなかったため、 `所得税控除の登録時に当該暦年を含む会計年度が存在しないというのがおかしな状況` ということに気づけていませんでした。

ですので エラーが出たことで、`まだ経理事務は発生しない未来だから会計年度マスタが存在しない` 状況もありうるのかと考えてしまいました。

>会計年度マスタが存在しない所得税控除マスタのデータがある という状況を入力チェックとして防ぐと良いのではないかと思いましたが、いかがでしょうか？

ご提案ありがとうございます！
入力チェックで防ぐ案、良いと思います。実装します。

**Comment by ichylinux** [comment]
確か、簡易入力や振替伝票による仕訳の登録時には、会計年度がなかったら入力チェックエラーになっていたかなと思います。

簡易入力や振替伝票は会計年度マスタがありき、というふうに所得税控除も会計年度マスタありき、という考えようとした場合に、少しエンティティ間の関係に関してバランスが悪いなと思いました。

* 会計年度・・・マスタデータ
* 簡易入力や振替伝票・・・トランザクションデータ
* 所得税控除・・・マスタデータ（？）

現在、所得税控除はマスタメンテのメニュー内にありますよね？
毎年社員の数だけデータ登録されると考えたら、これはトランザクションデータなのではないか、という見方ができるように思います。
そういった目線で見るなら、マスタメンテのメニュー内ではなく、人事労務のメニュー内を入り口にすることで、

* 会計年度・・・マスタデータ
* 簡易入力や振替伝票・・・トランザクションデータ
* 所得税控除・・・トランザクションデータ

という区分けにすると、会計年度マスタがありきだよね、という雰囲気が出るように思います。

**Comment by aomrikti** [comment]
ありがとうございます！
所得税控除はマスタメンテのメニュー内にあります。人事労務のメニュー内に移動して実装するようにいたします。

**Comment by aomrikti** [comment]
会計年度マスタにデータがあるかの入力チェックに加え、本締になっていないかの入力チェックも加えました。
＝＝＝

再現テストケース
- test/hr/exemptions_controller_test.rb
```rb
setup do  # 下記を追加
 @fiscal_year = FiscalYear.create!(company_id: Employee.not_deleted.first.company.id, fiscal_year: Date.today.year) 
end 
```
```rb
  def test_未登録の年度ヘの所得税控除の登録がエラーになること
    @fiscal_year.destroy!
    sign_in admin
    post :create, params: {exemption: valid_exemption_params}, xhr: true
    assert_response :success
    assert_template :new
    assert_equal ERR_FISCAL_YEAR_NOT_EXISTS, flash[:notice]
  end

  def test_本締の年度への所得税控除の登録がエラーになること
    @fiscal_year.update!(closing_status: CLOSING_STATUS_CLOSED)
    sign_in admin
    post :create, params: {exemption: valid_exemption_params}, xhr: true
    assert_response :success
    assert_template :new
    assert_equal ERR_CLOSING_STATUS_CLOSED, flash[:notice]
  end

    def test_未登録の年度ヘの所得税控除の更新がエラーになること
    @fiscal_year.destroy!
    sign_in admin
    patch :update, params: {id: exemption.id, exemption: valid_exemption_params}, xhr: true
    assert_response :success
    assert_template :edit
    assert_equal ERR_FISCAL_YEAR_NOT_EXISTS, flash[:notice]
  end
```

```
$ rails test

  1) Failure:
Hr::ExemptionsControllerTest#test_未登録の年度ヘの所得税控除の登録がエラーになること [test/controllers/hr/exemptions_controller_test.rb:70]:
expecting <"new"> but rendering with <["common/reload"]>

  2) Failure:
Hr::ExemptionsControllerTest#test_本締の年度への所得税控除の登録がエラーになること [test/controllers/hr/exemptions_controller_test.rb:79]:
expecting <"new"> but rendering with <["common/reload"]>

  3) Failure:
Hr::ExemptionsControllerTest#test_未登録の年度ヘの所得税控除の更新がエラーになること [test/controllers/hr/exemptions_controller_test.rb:106]:
expecting <"edit"> but rendering with <["common/reload"]>

443 runs, 3535 assertions, 3 failures, 0 errors, 0 skips
```

**Comment by aomrikti** [comment]
@ichylinux 
続くコメントが遅くなり申し訳ありません。
ステージングができない変更（削除）があり、解決に時間を要しておりました（上記コミットで解決済みです）。

>今回の仕様では、更新対象となるデータがそもそも追加されないだろうから、このテストケースは不要なんじゃないでしょうか？

現状では下記のように変更画面で暦年を変更できてしまうため、更新時のテストケースを追加しました。
編集画面では、暦年を変更できないように仕様を修正するようにいたします。


![スクリーンショット 2025-01-15 193210](https://github.com/user-attachments/assets/7f4e32cc-e1f0-481a-9496-2f2d022790e6)

**Comment by ichylinux** [comment]
@aomrikti 

なるほど、暦年を変更できる挙動なんですね。
変更できない仕様にしても問題なさそうですね。

**Comment by aomrikti** [comment]
ご確認ありがとうございます。
それでは上記の暦年を変更できない挙動に変更します。変更完了後、あらためて報告いたします。

**Comment by aomrikti** [comment]
追加したテストケース
- features/04.人事労務/02.所得税控除/01.所得税控除
```
  シナリオ: 編集ダイアログ内の暦年のセレクトボックスは無効化される
    前提 所得税控除の暦年は会計年度マスタに登録されている
    前提 経理次郎がログインしている
    前提 人事労務から所得税控除のメニューを選択する

    * ダイアログ内の暦年のセレクトボックスは以下のように有効もしくは無効に切り替わる
     | 機能 | 暦年のセレクトボックス |
     | 編集 | 無効 |
     | 追加 | 有効 |
```

削除したテストケース
- test/hr/exemptions_controller_test.rb
test_未登録の年度ヘの所得税控除の更新がエラーになること

**Comment by aomrikti** [comment]
@ichylinux 
対応いたしました。
レビューをお願いします。
- テスト結果
```
$ bundle exec rake dad:test features/04.人事労務/02.所得税 控除/01.所得税控除.feature

2 scenarios (2 passed)
9 steps (9 passed)
0m33.673s
```
```
$ rails test
Running via Spring preloader in process 13875
Run options: --seed 55328

Finished in 214.383485s, 2.0617 runs/s, 16.4891 assertions/s.

442 runs, 3535 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by aomrikti** [comment]
エビデンスを補足いたします。
- 所得税控除のダイアログ
![スクリーンショット 2025-01-16 141012](https://github.com/user-attachments/assets/739106f3-344a-4670-a260-992a71c96bca)
![image](https://github.com/user-attachments/assets/f8af6913-60c6-4b84-b986-cd0a6f3d620c)
![スクリーンショット 2025-01-16 143232](https://github.com/user-attachments/assets/f0ca4ad1-0e2a-49d4-a5b9-84973e261708)
![image](https://github.com/user-attachments/assets/2f5aa7f3-aeb6-4062-9716-9e54a6977b07)


- 人事労務のメニュー（所得税控除あり）
![image](https://github.com/user-attachments/assets/55006b03-e65a-478a-98b5-cc43013d251d)
- マスタメンテのメニュー（所得税控除なし）
![image](https://github.com/user-attachments/assets/f1c0a72e-820c-4bd6-8b2b-9c813631c8e4)

**Comment by aomrikti** [comment]
- setup_view_attributesについて
exemptions_controller.rbのcreateアクション内に `setup_view_attributes` という定義されていないメソッドがありました。
他のファイルではビューに渡すためのインスタンス変数を設定するメソッドとして使われています。
所得税控除のフォームでは不要と考えますので削除しました。
```rb
  def create
    @c = Exemption.new(exempiton_params)
    begin
      @c.transaction do
        @c.save!
      end

      flash[:notice] = '所得税控除情報を追加しました。'
      render 'common/reload'
    rescue => e
      # setup_view_attributes　削除しました。
      handle(e)
      render 'new'
    end
  end
```

**Comment by ichylinux** [comment]
@aomrikti 

ご対応ありがとうございます。

Exemption.fiscal_year の実装を見ていて、これまで意識してなかったのですが、あまり年度と暦年の関係性についてきちんと理解していない自分に気がつきました。

例えば、年度の2024と、暦年の2024 というのは常に等しいということであっているでしょうか？
暦年については1月～12月の12ヶ月というのは、世界、少なくとも日本国においては共通だと思います。
年度については、公的期間であれば4月～3月、多数の企業においても4月～3月の12ヶ月だろうと思います。

しかし、企業によってはその限りではありません。

例えばマイクロソフト日本法人だと確か7月～6月の12ヶ月ですね。
https://news.microsoft.com/ja-jp/2020/11/19/201119-fy21-microsoft-japan-new-year-management-policy/
```
日本マイクロソフト株式会社 (本社: 東京都港区) の 2021 会計年度 (2020 年 7 月 ～ 2021 年 6 月) における経営方針について、概要を以下のとおりご紹介します。
...
...
```

Exemption.fiscal_year の実装、下記で常に正しいと言えるでしょうか？
```ruby
FiscalYear.find_by(company_id: company_id, fiscal_year: yyyy)
```

ちょっと確認・調査をお願いします。

**Comment by ichylinux** [comment]
@aomrikti 

調査ありがとうございます。

> 年末調整の処理について調べたところ、会計年度について触れた内容のものを見つけることができませんでした。

これはなさそうですね。本質的に年末調整に会計年度は関係しないと思われます。

> どう両者が関係するのか把握できていません。

ということで、関係しないと思います。法が決めていることなら従うまでなのですが。
なので、これについてはアプリ（Hyacc）でどうするかという仕様を決める必要がありますね。

> 代替案として、確定申告の期限にあわせて、暦年の翌4月以降になれば編集・削除ボタンを非表示にするというのはいかがでしょうか？

どこかで編集・削除をできなくする、という方向性はそのとおりに思います。
以下、こちらの考察です。

企業が行う年末調整の申告書の提出期限は遅くとも翌年１月末ということなので、１月末を過ぎた4月まで編集可能でも2月や3月の編集内容を給与支給時の還付に間に合わすことはできませんね。
最大でも1月末までだろうと思います。

また、1月から12月までの所得税の計算なので、12月までの給与によって計算され、計算結果として仕訳も12月付けとなるかと思います。
年末調整の事務処理が1月にずれ込んでも、処理結果となる仕訳は12月分として登録します。

| ![Image](https://github.com/user-attachments/assets/5d1c148e-7c9f-4a32-99cd-bfb9ccd6d6b9) |
|-|

ただし、ここは企業によってことなるでしょうか、計算結果を12月分の仕訳にしなければいけないというルールはなさそうです。
1月分の給与に反映して従業員に還付しても良いように思います。
https://www.freee.co.jp/kb/kb-payroll/yearend-adjustment-period/
```
年末調整の結果、本来納めるべき所得税額より源泉徴収税額のほうが多ければ従業員に差額分が還付され、源泉徴収税額のほうが少なければ不足分が徴収されます。還付や徴収は、12月または1月の給与支払い時に行われることが一般的です。
```

したがって、12月を含む会計年度は、1月から新会計年度になるとしても、年末調整が済むまでは本締めにすることはできません。
1月まで事務処理がずれ込んだ場合で12月が昨会計年度だったとしても、まだ本締めにはしないで事務処理を行います。
あるいは、1月の給与に反映するなら、1月を含む会計年度は本締めにはしない、という具合でしょうか。

ということで、本締めになっているかどうかをチェックすべき会計年度は、12月を含む会計年度、という定義が導き出されるように思います。

マイクロソフトの例だと、暦年2020年の所得税控除は、2020年12月を含む会計年度 2021 年が本締めになっていなければ、追加・編集・削除できる、ということでいかがでしょうか？

もし、1月を含む会計年度、という12月固定が不適切になった場合には、会社マスタで、年末調整の還付月がいつなのかを管理できるように今後拡張の余地はあるので、まずは12月固定で良いかなと思います。

**Comment by aomrikti** [comment]
@ichylinux 
ご説明ありがとうございます。
所得税控除を給与に反映するために、会計年度の締め状態をチェックするという仕組みが必要であることが理解いたしました。

`12月を含む会計年度` を取得するために、fiscal_yearメソッドを以下のメソッド名に変更しました。
会計年度2020年＝期首月がichylinux 
ご説明ありがとうございます。
所得税控除を給与に反映するために、会計年度の締め状態をチェックするという仕組みが必要であることが理解いたしました。

`12月を含む会計年度` を取得するために、fiscal_yearメソッドから fiscal_year_including_december_of_yyyyメソッドにに名前を変更しました。
会計年度2020年の場合、期首が2020年1月～2020年12月のいずれかに設定されている=会計年度2020年であれば2020年12月は含まれることから、処理は下記のままで名前のみの変更です。
- app/models/exemption.rb
```rb
  def fiscal_year_including_december_of_yyyy
    FiscalYear.find_by(company_id: company_id, fiscal_year: yyyy)
  end
```
メソッド名を変更後もテストが通ることを確認しました。
```
$ rails test test/controllers/hr/exemptions_controller_test.rb
.......

Finished in 11.993833s, 0.8338 runs/s, 3.0849 assertions/s.

10 runs, 37 assertions, 0 failures, 0 errors, 0 skips
```
```
$ bundle exec rake dad:test features/04.人事労務/02.所得税 控除/01.所得税控除.feature

2 scenarios (2 passed)
9 steps (9 passed)
0m35.183s
```

**Comment by ichylinux** [comment]
@aomrikti 

ご対応ありがとうございます。

先のマイクロソフトのケースにおいても問題なく適切な暦年と会計年度の関係になっているということであっていますか？

**Comment by aomrikti** [comment]
@ichylinux 
>先のマイクロソフトのケースにおいても問題なく適切な暦年と会計年度の関係になっているということであっていますか？

誤っていますね。
期首が6月以前、7月以降で会計年度が変わるということを理解できておりませんでした。理解の誤りに気づきました。

下記のように、fiscal_year_including_december_of_yyyyメソッドを修正いたしました。
- app/models/exemption.rb
```rb
  def fiscal_year_including_december_of_yyyy
    yyyymm = yyyy * 100 + 12
    Company.find(company_id).get_fiscal_year(yyyymm)
  end
```

**Comment by ichylinux** [comment]
@aomrikti 

ご対応ありがとうございます。

GitHub上で差分を見ている感じでは良い具合になったように思います。
それではリファクタリング要素がないかも含めて、ソースレビューを実施していこうと思います！

**Comment by aomrikti** [comment]
よろしくお願いいたします。

**Comment by ichylinux** [comment]
@aomrikti 

ご対応ありがとうございます。

当初、ビューファイル内で締め状態を確認するためのコードが記載されていました。

```
<% unless FiscalYear.find_by(company_id: e.company_id, fiscal_year: e.yyyy).closed? %>
```

このあたり、ロジックをベタ書きすると、MVCの役割分担としては、ビューからデータベース問い合わせしているような状態であんまりきれいではありませんでした。
ビュー専用のロジックであればヘルパーメソッド、ビュー以外でも使えるのであればモデルのメソッドと、実装箇所の責任分担が必要に思っていました。

この点ですが、最終的にはみごとにモデルのメソッドとして実装され、しかもテストケースでロジックに不備がないことも担保されています。

ソースレビューを実施していこうと思いますと発言しましたが、レビュー結果として特に指摘はありませんでした。

少しリファクタリングはしましたが、良く実装できているので master に取り込みました。
